# Generated by Django 4.2.2 on 2023-07-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('messenger', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
            ],
        ),
    ]
